export const tagTypes = {
  users: "users",
  services: "services",
  dashboard: "dashboard",
  analytics: "analytics",
  notifications: "notifications",
  bookings: "bookings",
  transactions: "transactions",
  managers: "managers",
  workers: "workers",
  states: "states",
  profile: "profile",
  privacy: "privacy",
  termsCondition: "termsCondition",
  helpSupport: "helpSupport",
  siteContent: "siteContent",
};

export const tagTypesList = [
  tagTypes.analytics,
  tagTypes.bookings,
  tagTypes.dashboard,
  tagTypes.helpSupport,
  tagTypes.notifications,
  tagTypes.transactions,
  tagTypes.managers,
  tagTypes.workers,
  tagTypes.services,
  tagTypes.states,
  tagTypes.privacy,
  tagTypes.profile,
  tagTypes.termsCondition,
  tagTypes.users,
  tagTypes.siteContent,
];
